#!/bin/bash
set -e

echo "--- Illnet Rx Remote Scanner Setup ---"
echo "This script will help you configure this scanner to connect to a remote host."
echo

# --- SSH Key Setup ---
SSH_KEY_PATH="$HOME/.ssh/id_rsa"
if [ ! -f "$SSH_KEY_PATH" ]; then
    echo "[*] No existing SSH key found at $SSH_KEY_PATH."
    # Check if running in an interactive terminal
    if [ -t 0 ]; then
        read -p "Would you like to generate a new SSH key now? (y/n) " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            ssh-keygen -t rsa -b 4096 -N "" -f "$SSH_KEY_PATH"
            echo "[*] New SSH key generated."
        else
            echo "[!] SSH key is required. Please generate one and run this script again." >&2
            exit 1
        fi
    else
        echo "[*] Non-interactive mode detected. Generating new SSH key automatically."
        ssh-keygen -t rsa -b 4096 -N "" -f "$SSH_KEY_PATH"
        echo "[*] New SSH key generated."
    fi
else
    echo "[*] Existing SSH key found at $SSH_KEY_PATH."
fi
echo

# --- Remote Host & API Key Configuration ---
if [ -t 0 ]; then # Interactive mode
    read -p "Enter the remote host's IP address or hostname: " REMOTE_HOST
    while [ -z "$REMOTE_HOST" ]; do
        read -p "Remote host cannot be empty. Please enter it again: " REMOTE_HOST
    done

    read -p "Enter the username for the remote host (e.g., ubuntu, ec2-user, root): " REMOTE_USER
    while [ -z "$REMOTE_USER" ]; do
        read -p "Remote user cannot be empty. Please enter it again: " REMOTE_USER
    done

    read -sp "Enter your OpenAI API Key (it will not be displayed): " OPENAI_API_KEY
    while [ -z "$OPENAI_API_KEY" ]; do
        echo
        read -sp "OpenAI API Key cannot be empty. Please enter it again: " OPENAI_API_KEY
    done
    echo
else # Non-interactive mode
    echo "[*] Non-interactive mode. Reading configuration from environment variables."
    if [ -z "${REMOTE_HOST-}" ] || [ -z "${REMOTE_USER-}" ] || [ -z "${OPENAI_API_KEY-}" ]; then
        echo "[!] In non-interactive mode, you must provide REMOTE_HOST, REMOTE_USER, and OPENAI_API_KEY as environment variables." >&2
        echo "Example: export REMOTE_HOST=... && curl ... | bash" >&2
        exit 1
    fi
    echo "[*] Configuration loaded from environment variables."
fi
echo

# --- SSH Key Distribution ---
if [ -t 0 ]; then # Interactive mode
    echo "[*] Now, I will copy your public SSH key to the remote host."
    echo "You will be prompted for the remote user's password."
    if ssh-copy-id "${REMOTE_USER}@${REMOTE_HOST}"; then
        echo "[*] SSH key successfully copied."
    else
        echo "[!] Failed to copy SSH key. Please check your connection and credentials." >&2
        exit 1
    fi
else # Non-interactive mode
    echo
    echo "--- ACTION REQUIRED ---"
    echo "[!] In non-interactive mode, you must manually add the public key to the remote host."
    echo "Log into '${REMOTE_HOST}' as user '${REMOTE_USER}' and add the following line to '~/.ssh/authorized_keys':"
    echo "----"
    cat "${SSH_KEY_PATH}.pub"
    echo "----"
    echo "The application will not be able to connect until you complete this step."
    echo
fi
echo

# --- Create .env file ---
echo "[*] Creating the .env file for Docker Compose..."
# Create the Illnet-Rx directory if it doesn't exist
mkdir -p Illnet-Rx
cat > Illnet-Rx/.env << EOL
# This file is automatically generated by the setup.sh script
# Docker Compose will use these variables to configure the application

# Remote scanning configuration
REMOTE_HOST=${REMOTE_HOST}
REMOTE_USER=${REMOTE_USER}

# OpenAI API Key for report analysis
OPENAI_API_KEY=${OPENAI_API_KEY}

# Default credentials for the web UI (change these for better security)
ADMIN_USER=admin
ADMIN_PASSWORD=password

# Cron expression for scheduled scans (e.g., '0 2 * * *' for 2 AM daily). Leave empty to disable.
SCAN_SCHEDULE=
EOL
echo "[*] '.env' file created successfully in the 'Illnet-Rx' directory."
echo
echo "--- Setup Complete! ---"
echo
echo "You can now start the application by running:"
echo "  docker-compose up --build -d"
echo
echo "Then, open your browser to http://localhost:5001 to run a scan."
echo "The scan will be performed on '${REMOTE_HOST}' as user '${REMOTE_USER}'."