#!/bin/bash
set -e

echo "--- Illnet Rx Remote Scanner Setup ---"
echo "This script will help you configure this scanner to connect to a remote host."
echo

# Check for required tools
if ! command -v ssh-keygen >/dev/null 2>&1 || ! command -v ssh-copy-id >/dev/null 2>&1; then
    echo "[!] 'ssh-keygen' and 'ssh-copy-id' are required for this setup." >&2
    echo "Please install your system's OpenSSH client package and run this script again." >&2
    exit 1
fi

# --- SSH Key Setup ---
SSH_KEY_PATH="$HOME/.ssh/id_rsa"
if [ ! -f "$SSH_KEY_PATH" ]; then
    echo "[*] No existing SSH key found at $SSH_KEY_PATH."
    read -p "Would you like to generate a new SSH key now? (y/n) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        ssh-keygen -t rsa -b 4096 -N "" -f "$SSH_KEY_PATH"
        echo "[*] New SSH key generated."
    else
        echo "[!] SSH key is required. Please generate one and run this script again." >&2
        exit 1
    fi
else
    echo "[*] Existing SSH key found at $SSH_KEY_PATH."
fi

echo
echo "--- Remote Host Configuration ---"

# --- Get Remote Host Details ---
read -p "Enter the remote host's IP address or hostname: " REMOTE_HOST
while [ -z "$REMOTE_HOST" ]; do
    read -p "Remote host cannot be empty. Please enter it again: " REMOTE_HOST
done

read -p "Enter the username for the remote host (e.g., ubuntu, ec2-user, root): " REMOTE_USER
while [ -z "$REMOTE_USER" ]; do
    read -p "Remote user cannot be empty. Please enter it again: " REMOTE_USER
done

echo
echo "[*] Now, I will copy your public SSH key to the remote host."
echo "You will be prompted for the remote user's password."
if ssh-copy-id "${REMOTE_USER}@${REMOTE_HOST}"; then
    echo "[*] SSH key successfully copied."
else
    echo "[!] Failed to copy SSH key. Please check your connection and credentials." >&2
    exit 1
fi

echo
echo "--- API Key Configuration ---"
read -sp "Enter your OpenAI API Key (it will not be displayed): " OPENAI_API_KEY
while [ -z "$OPENAI_API_KEY" ]; do
    echo
    read -sp "OpenAI API Key cannot be empty. Please enter it again: " OPENAI_API_KEY
done
echo

# --- Create .env file ---
echo
echo "[*] Creating the .env file for Docker Compose..."
cat > .env << EOL
# This file is automatically generated by the setup.sh script
# Docker Compose will use these variables to configure the application

# Remote scanning configuration
REMOTE_HOST=${REMOTE_HOST}
REMOTE_USER=${REMOTE_USER}

# OpenAI API Key for report analysis
OPENAI_API_KEY=${OPENAI_API_KEY}

# You can add other optional variables here, for example:
# SLACK_WEBHOOK_URL=...
# ALERT_EMAIL_TO=...
EOL

echo "[*] '.env' file created successfully."
echo
echo "--- Setup Complete! ---"
echo
echo "You can now start the application by running:"
echo "  docker-compose up --build -d"
echo
echo "Then, open your browser to http://localhost:5001 to run a scan."
echo "The scan will be performed on '${REMOTE_HOST}' as user '${REMOTE_USER}'."
